"""Added Asset table

Revision ID: 5dd509ed82f8
Revises: 925a5910c076
Create Date: 2024-11-30 12:11:33.430245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dd509ed82f8'
down_revision = '925a5910c076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('assetSymbol', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=False))
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('price')
        batch_op.drop_column('created_at')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('amount')
        batch_op.drop_column('assetSymbol')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
