"""Add pin field to User table

Revision ID: 624d4b0e91dc
Revises: c0425da03dd3
Create Date: 2024-11-23 21:08:15.172624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624d4b0e91dc'
down_revision = 'c0425da03dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin')

    # ### end Alembic commands ###
