"""Add OTP model

Revision ID: 70de53917303
Revises: 1dd5f370667c
Create Date: 2024-11-22 15:43:49.992555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70de53917303'
down_revision = '1dd5f370667c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_column('current_datetime')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('otp')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
