"""Add phoneNumber to User

Revision ID: 7f32d52c2913
Revises: 
Create Date: 2024-11-20 15:46:47.502506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f32d52c2913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('phoneNumber', sa.String(length=15), nullable=False))
        # batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        # batch_op.add_column(sa.Column('accountNumber', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['accountNumber'])
        batch_op.create_unique_constraint(None, ['phoneNumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('accountNumber')
        batch_op.drop_column('address')
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
