"""Updated transactions model

Revision ID: 925a5910c076
Revises: f028a35d30b7
Create Date: 2024-11-29 16:10:53.242494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925a5910c076'
down_revision = 'f028a35d30b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key('transaction_ibfk_2', 'user', ['source_account_number'], ['accountNumber'])

    # ### end Alembic commands ###
