"""Updated name of assetSymbol to asset_symbol in Asset table

Revision ID: 97d33deca2e3
Revises: 5dd509ed82f8
Create Date: 2024-11-30 14:47:08.187618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97d33deca2e3'
down_revision = '5dd509ed82f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_symbol', sa.String(length=10), nullable=False))
        batch_op.drop_column('assetSymbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assetSymbol', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('asset_symbol')

    # ### end Alembic commands ###
